# Generated by Django 5.1.3 on 2025-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_customuser_managers_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='description',
            new_name='reason_for_leave',
        ),
        migrations.AddField(
            model_name='leave',
            name='person_detailed_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='place_of_application',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='post_held',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='sanctioned_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='sanctioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Earned Leave', 'Earned Leave'), ('Privilege Leave', 'Privilege Leave'), ('Leave Without Pay', 'Leave Without Pay'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
