# Generated by Django 5.1.3 on 2025-02-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_rename_description_leave_reason_for_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='person_detailed_to',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='place_of_application',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='post_held',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='reason_for_leave',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='sanctioned_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='sanctioned_date',
        ),
        migrations.AddField(
            model_name='faculty',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='total_leaves',
            field=models.IntegerField(default=30),
        ),
    ]
