# Generated by Django 5.1.3 on 2025-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
