# Generated by Django 5.1.3 on 2025-03-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_alter_faculty_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentitlement',
            name='faculty_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Non-Teaching', 'Non-Teaching')], max_length=50, unique=True),
        ),
    ]
